// src/i18n/translations/about.ts
import type { TranslationDict } from '../types';

export const about: TranslationDict = {
  'about.title': { en: 'About', ru: 'О приложении', be: 'Пра праграму', lt: 'Apie', pl: 'O aplikacji', uk: 'Про додаток' },
  'about.tagline': { en: 'Find grounds. Join the game.', ru: 'Находите площадки. Играйте.', be: 'Знаходзьце пляцоўкі. Гуляйце.', lt: 'Raskite aikšteles. Žaiskite.', pl: 'Znajdź boiska. Graj.', uk: 'Знаходьте майданчики. Грайте.' },
  'about.description': { en: 'PlayG helps you discover outdoor sports grounds near you and join local games. Explore the map, find a court or pitch, and jump into events hosted by your community — or start your own in a few taps.', ru: 'PlayG помогает находить спортивные площадки рядом и присоединяться к играм. Исследуйте карту, находите корты и присоединяйтесь к событиям сообщества — или создавайте свои в пару касаний.', be: 'PlayG дапамагае знаходзіць спартыўныя пляцоўкі побач і далучацца да гульняў. Даследуйце карту, знаходзьце корты і далучайцеся да падзей супольнасці — або стварайце свае ў пару дотыкаў.', lt: 'PlayG padeda rasti sporto aikšteles netoliese ir prisijungti prie vietinių žaidimų. Naršykite žemėlapį, raskite aikšteles ir prisijunkite prie bendruomenės renginių — arba kurkite savo keliais paspaudimais.', pl: 'PlayG pomaga odkrywać boiska sportowe w pobliżu i dołączać do lokalnych gier. Przeglądaj mapę, znajdź kort lub boisko i dołącz do wydarzeń swojej społeczności — lub stwórz własne w kilku krokach.', uk: 'PlayG допомагає знаходити спортивні майданчики поруч і долучатися до ігор. Досліджуйте карту, знаходьте корти та долучайтеся до подій спільноти — або створюйте власні за кілька дотиків.' },
  'about.feature.discover.title': { en: 'Discover grounds', ru: 'Находите площадки', be: 'Знаходзьце пляцоўкі', lt: 'Atraskite aikšteles', pl: 'Odkrywaj boiska', uk: 'Знаходьте майданчики' },
  'about.feature.discover.subtitle': { en: 'Maps, search and ratings for spots near you.', ru: 'Карты, поиск и рейтинги мест рядом.', be: 'Карты, пошук і рэйтынгі месцаў побач.', lt: 'Žemėlapiai, paieška ir netoliese esančių vietų reitingai.', pl: 'Mapy, wyszukiwanie i oceny miejsc w pobliżu.', uk: 'Карти, пошук і рейтинги місць поруч.' },
  'about.feature.join.title': { en: 'Join events', ru: 'Присоединяйтесь к событиям', be: 'Далучайцеся да падзей', lt: 'Prisijunkite prie renginių', pl: 'Dołączaj do wydarzeń', uk: 'Долучайтеся до подій' },
  'about.feature.join.subtitle': { en: 'Find games by day, sport and skill level.', ru: 'Ищите игры по дате, виду спорта и уровню.', be: 'Шукайце гульні па даце, відзе спорту і ўзроўні.', lt: 'Raskite žaidimus pagal dieną, sportą ir lygį.', pl: 'Znajdź gry według dnia, sportu i poziomu.', uk: 'Знаходьте ігри за датою, видом спорту та рівнем.' },
  'about.feature.play.title': { en: 'Play together', ru: 'Играйте вместе', be: 'Гуляйце разам', lt: 'Žaiskite kartu', pl: 'Grajcie razem', uk: 'Грайте разом' },
  'about.feature.play.subtitle': { en: 'A friendly, community-first experience.', ru: 'Дружелюбный опыт, ориентированный на сообщество.', be: 'Сяброўскі досвед, арыентаваны на супольнасць.', lt: 'Draugiška patirtis, orientuota į bendruomenę.', pl: 'Przyjazne doświadczenie nastawione na społeczność.', uk: 'Дружній досвід, орієнтований на спільноту.' },
  'about.version': { en: 'Version 1.0.0 · Made for players', ru: 'Версия 1.0.0 · Сделано для игроков', be: 'Версія 1.0.0 · Зроблена для гульцоў', lt: 'Versija 1.0.0 · Skirta žaidėjams', pl: 'Wersja 1.0.0 · Stworzone dla graczy', uk: 'Версія 1.0.0 · Зроблено для гравців' },
};